### ISSUE TITLE
werkzeug >=3.0 is required, but raises error in patch_flask

### ISSUE THREAD

**Issue by eschibli** [microsoft/azureml-inference-server#90]
`werkzeug` 3.0 [removed](https://github.com/search?q=repo%3Apallets%2Fwerkzeug%20__version__&type=code) the __version__ attribute, which is accessed in the patch_flask function that runs on startup. 

Line 33 in `create_app.py` should not be necessary anymore since werkzeug>=3.0 is required now.

**Comment by jayakrishnaMan** [comment]
I am also facing the same issue and it's failing all my deployments. Is there any fix available?

``` 
2024-11-10 14:54:18,146 W [71] azmlinfsrv - AML_FLASK_ONE_COMPATIBILITY is set. However, compatibility patch for Flask 1 has failed. This is only a problem if you use @rawhttp and relies on deprecated methods such as has_key().
Traceback (most recent call last):
  File "/opt/miniconda/envs/azureml_env2e888c9a6d4b4128a74cf7c24c396821/lib/python3.10/site-packages/azureml_inference_server_http/server/create_app.py", line 58, in <module>
    patch_flask()
  File "/opt/miniconda/envs/azureml_env2e888c9a6d4b4128a74cf7c24c396821/lib/python3.10/site-packages/azureml_inference_server_http/server/create_app.py", line 33, in patch_flask
    patch_werkzeug = LooseVersion(werkzeug.__version__) >= LooseVersion("2.1")
AttributeError: module 'werkzeug' has no attribute '__version__'```

**Comment by riccardotrevisan** [comment]
Not sure deployments fail due to that error.
Paste full log and check also issue [#3415](https://github.com/Azure/azureml-examples/issues/3415) (azure-examples).

**Comment by jayakrishnaMan** [comment]
Sure will check it out. I am also facing error "
Failed to test model: Network Error" once it finishes
